[profile.default]
src = 'src'
out = 'foundry-out'
solc_version = '0.8.24'
libs = ["lib"]
evm_version = 'cancun'
via_ir = true
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
